name: ci

on:
  push:
    branches:
      - 'master'
      - 'containers'
    tags:
      - 'v*'
  pull_request:

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Docker repo name
        id: reponame
        run: |
          echo "repo=${GITHUB_REPOSITORY}" | tr '[:upper:]' '[:lower:]' > "${GITHUB_OUTPUT}"

      - name: Docker tags setup
        uses: docker/metadata-action@v4
        id: meta
        with:
          images: ${{ steps.reponame.outputs.repo }}

      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
